database:
  enabled: true
  type: mysql

  mysql:
    host: localhost
    port: 3306
    user: carbon
    password: carbon123
    database: carbon_db
    ssl_mode: "false"
    max_open_conns: 25
    max_idle_conns: 5
    conn_max_lifetime: 300
